import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>MY ART GALLERY</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='ART GALLERY BY Ashima Yadav' message='As a artist, I tell a story with my work in painting, canvas. "I would like to paint the way a bird sings..."' />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
